# This workflow will upload a Python Package using Twine when a release is created

name: pypi-publish

# Controls when the workflow will run
on:
  workflow_dispatch: {}
  release:
    types: [ published ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Set env vars
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    - name: Create packages
      run: python -m build
    - name: Run twine check
      run: twine check dist/*
    - name: Upload to pypi
      run: twine upload dist/*.whl
